//! N-API bindings for `model_api_client::SyncClient`.
//!
//! The TypeScript surface (generated by `napi build --release`
//! into `index.d.ts`) is roughly:
//!
//! ```ts
//! export class Client {
//!   static connect(socketPath: string): Promise<Client>
//!   readonly modelName: string
//!   readonly gpuMemoryMb: number | null
//!   readonly protocolVersion: number
//!   inference(req: InferenceRequest): Promise<InferenceResponse>
//!   shutdown(): Promise<void>
//! }
//! export interface InferenceRequest {
//!   role: 'fast' | 'deep' | 'asr' | 'omni'
//!   input: string                  // text only for now
//!   maxTokens: number
//!   sessionId?: string             // omit → Stateless
//!   cacheHash?: number             // bigint (u64)
//!   disableThinkPrefix?: boolean
//! }
//! export interface InferenceResponse {
//!   text: string
//!   sessionId?: string
//!   rawText?: string
//!   injections: string[]
//! }
//! ```
//!
//! All methods are Promise-returning. Under the hood, each call
//! wraps a sync `SyncClient` method in `tokio::task::spawn_blocking`
//! so the Node event loop isn't blocked. The `SyncClient` itself is
//! held in an `Arc<Mutex>`-style shape (it has internal mutex) so
//! concurrent `inference()` calls from multiple async callers
//! serialize behind the single UDS connection.

use std::sync::Arc;

use napi::bindgen_prelude::*;
use napi_derive::napi;

use model_api_client::SyncClient;
use model_api_proto as proto;

// ── Wire-shape mirrors (JS-friendly camelCase + Strings) ────────────

/// Inference request as seen from JS. Mirrors a subset of
/// `model_api_proto::InferenceRequest`: only the bits that make
/// sense to expose to a script. Streaming + progress are TODOs —
/// when wired, they'd take a callback (napi `ThreadsafeFunction`)
/// per channel.
#[napi(object)]
#[derive(Clone)]
pub struct InferenceRequest {
    /// One of `"fast"`, `"deep"`, `"asr"`, `"omni"`.
    pub role: String,
    /// Text prompt. (PCM/Mel are not yet exposed; add when needed.)
    pub input: String,
    pub max_tokens: u32,
    /// Optional session id. Absent = stateless one-shot. Empty
    /// string = ask the server to create a fresh persistent
    /// session.
    pub session_id: Option<String>,
    /// Conversation Merkle root. Pass 0 (or omit) when the caller
    /// doesn't track one; the server's KV-cache logic uses it to
    /// short-circuit delta-prefill.
    pub cache_hash: Option<BigInt>,
    /// Skip prefilling the `<think>\n` prefix at the start of the
    /// assistant turn. Useful for chat-completion APIs that don't
    /// want a chain-of-thought block in the response.
    pub disable_think_prefix: Option<bool>,
}

/// Inference response shape returned to JS.
#[napi(object)]
pub struct InferenceResponse {
    /// Cleaned answer text (think blocks already stripped).
    pub text: String,
    /// Session id from the server, if a session was created or
    /// continued.
    pub session_id: Option<String>,
    /// Raw model output, including `<think>...</think>` and any
    /// injected tool-response blocks. Use for transcript logging.
    pub raw_text: Option<String>,
    /// Tool-response bodies the dispatcher spliced in during
    /// generation, in order. Empty when no injections fired.
    pub injections: Vec<String>,
}

// ── Client ─────────────────────────────────────────────────────────

/// Connected client. Hold one per logical inference channel; the
/// server serializes requests behind a single slot regardless of
/// how many `Client`s connect, so multiple instances don't add
/// throughput but do let independent callers proceed without
/// blocking each other locally.
#[napi]
pub struct Client {
    /// Wrapped in Arc so `spawn_blocking` closures can move a clone
    /// without taking ownership of `&self`.
    inner: Arc<SyncClient>,
}

#[napi]
impl Client {
    /// Connect to a model_api server on `socketPath`. Performs the
    /// Hello handshake; rejects the Promise on connect / handshake
    /// failure.
    #[napi(factory)]
    pub async fn connect(socket_path: String) -> Result<Client> {
        let inner = tokio::task::spawn_blocking(move || SyncClient::connect(socket_path))
            .await
            .map_err(|e| Error::from_reason(format!("join: {e}")))?
            .map_err(|e| Error::from_reason(format!("{e}")))?;
        Ok(Self { inner: Arc::new(inner) })
    }

    /// The server-reported model name (e.g. `"gemma-4-26b"`).
    #[napi(getter)]
    pub fn model_name(&self) -> String {
        self.inner.server_info().model_name.clone()
    }

    /// Best-effort GPU memory in megabytes; `null` for CPU-only.
    #[napi(getter)]
    pub fn gpu_memory_mb(&self) -> Option<u32> {
        self.inner.server_info().gpu_memory_mb
    }

    /// Wire protocol version the server advertised. Useful for
    /// client-side feature-gating against future protocol bumps.
    #[napi(getter)]
    pub fn protocol_version(&self) -> u32 {
        self.inner.server_info().protocol_version
    }

    /// Submit one inference request. Resolves with the final
    /// response; rejects on server `InferenceError` or transport
    /// failure. Concurrent calls from different async tasks
    /// serialize behind the connection's internal mutex.
    #[napi]
    pub async fn inference(&self, req: InferenceRequest) -> Result<InferenceResponse> {
        let inner = self.inner.clone();
        let proto_req = to_proto_request(req)
            .map_err(|e| Error::from_reason(format!("bad request: {e}")))?;
        let resp = tokio::task::spawn_blocking(move || inner.inference(proto_req))
            .await
            .map_err(|e| Error::from_reason(format!("join: {e}")))?
            .map_err(|e| Error::from_reason(format!("{e}")))?;
        Ok(from_proto_response(resp))
    }

    /// Ask the server to drain its queue and exit. Resolves once
    /// the server's `Goodbye` arrives (or on disconnect — both are
    /// considered clean).
    #[napi]
    pub async fn shutdown(&self) -> Result<()> {
        let inner = self.inner.clone();
        tokio::task::spawn_blocking(move || inner.shutdown())
            .await
            .map_err(|e| Error::from_reason(format!("join: {e}")))?
            .map_err(|e| Error::from_reason(format!("{e}")))?;
        Ok(())
    }
}

// ── Translation helpers ─────────────────────────────────────────────

fn to_proto_request(r: InferenceRequest) -> std::result::Result<proto::InferenceRequest, String> {
    let role = match r.role.as_str() {
        "fast" => proto::GpuRole::Fast,
        "deep" => proto::GpuRole::Deep,
        "asr" => proto::GpuRole::Asr,
        "omni" => proto::GpuRole::Omni,
        other => return Err(format!(
            "role must be one of 'fast', 'deep', 'asr', 'omni'; got {other:?}"
        )),
    };
    let cache_hash = r.cache_hash
        .map(|bi| bi.get_u64().1)  // (sign_bit, value, lossless?)
        .unwrap_or(0);
    Ok(proto::InferenceRequest {
        role,
        input: proto::InferenceInput::Text(r.input),
        max_tokens: r.max_tokens,
        session: match r.session_id {
            None => proto::SessionMode::Stateless,
            Some(id) => proto::SessionMode::Persistent { session_id: id },
        },
        inference_config: proto::InferenceConfig {
            disable_think_prefix: r.disable_think_prefix.unwrap_or(false),
        },
        cache_hash,
        // Streaming + progress not yet wired through to JS; non-
        // streaming path returns one final response.
        stream: false,
        progress: false,
    })
}

fn from_proto_response(r: proto::InferenceResponse) -> InferenceResponse {
    InferenceResponse {
        text: r.text,
        session_id: r.session_id,
        raw_text: r.raw_text,
        injections: r.injections,
    }
}
